# D√©clencheurs du workflow :
# Ce workflow se d√©clenche automatiquement lorsqu'un push est effectu√© sur la branche main.
on:
  push:
    branches:
      - main

jobs:
  push_to_registries:
    # Nom du workflow : ce nom sera affich√© dans l'interface GitHub Actions.
    name: Build, Scan and Push Docker Image
    # Sp√©cifie l'environnement d'ex√©cution : ici, une machine virtuelle Ubuntu.
    runs-on: ubuntu-latest

    # Permissions n√©cessaires pour publier sur GitHub Packages.
    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write

    steps:
      # √âtape 1 : R√©cup√®re le code source du d√©p√¥t
      - name: Checkout code
        uses: actions/checkout@v3

      # √âtape 2 : Configurer Docker Buildx pour des fonctionnalit√©s avanc√©es.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Docker Buildx est une extension de Docker qui permet de construire des images optimis√©es (multi-plateformes, parall√©lisation, etc.).


      # √âtape 3 : Connexion au registre Docker GitHub Container Registry (ghcr.io).
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # - registry : sp√©cifie l'adresse du registre Docker (ici, GitHub Container Registry).
          # - username : utilise l'identifiant de l'utilisateur qui d√©clenche l'action.

      # √âtape 4 : Construire l'image Docker et la pousser dans le registre.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # D√©finit le r√©pertoire courant comme contexte de construction Docker (l√† o√π se trouve le Dockerfile).
          push: true # Indique que l'image doit √™tre pouss√©e automatiquement apr√®s la construction.
          
          # üö® CORRECTION : L'utilisateur laoukiliayoub41-del est utilis√© ici
          tags: ghcr.io/laoukiliayoub41-del/ue19-lab-05
          # Sp√©cifie le nom et le tag de l'image Docker :
          # - ghcr.io/laoukiliayoub41-del/ue19-lab-05 : chemin vers le registre.

      # √âtape 5 : V√©rification de l'image Docker pour les vuln√©rabilit√©s
      - name: Analyze Docker image with Trivy
        uses: aquasecurity/trivy-action@master # Utilise l'outil Trivy pour d√©tecter les failles de s√©curit√©
        with:
          # üö® CORRECTION : L'utilisateur laoukiliayoub41-del est utilis√© ici
          image-ref: ghcr.io/laoukiliayoub41-del/ue19-lab-05 # R√©f√©rence de l'image Docker √† scanner
